# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Women Techmakers Galicia 2016
email: info@gdgvigo.com
description: > # this means to ignore newlines until the next key
  Women Techmakers es una iniciativa liderada por Google, con un seguimiento mundial. Con motivo del Día Internacional
  de la Mujer, se celebran diferentes eventos alrededor del mundo para dar a conocer el trabajo y el conocimiento de
  las mujeres en el sector tecnológico.
about: > # this means to ignore newlines until the next key
  Organizado por GDG Vigo en colaboración con GDG Santiago, GDG Coruña, GDG Ourense y con el apoyo de nuestros sponsors
url: "http://wtm.gdgvigo.com" # the base hostname & protocol for your site
baseurl: "/wtm-galicia"

# Social media profiles - feel free to add more here
twitter_link: https://twitter.com/GDGVigo
google_plus_link: https://plus.google.com/u/0/communities/104458805154699272096

# Address information
address_link: https://goo.gl/maps/FDqSbVGz8Kp
address_venue: Círculo de Empresarios de Galicia
address_street: Avenida de García Barbón, 62
address_city: Vigo
address_zip: 36201

copyright: Women Techmakers Spain, part of <a target="_blank" href="https://www.womentechmakers.com">WomenTechmakers</a>
# Build settings
markdown: kramdown

collections:
 speakers:
   output: true
